### ISSUE TITLE
Feature request: Operator overloads for TA::DistArray

### ISSUE THREAD

**Issue by bimalgaudel** [ValeevGroup/tiledarray#168]
It would be useful, at least in SeQuant2, to have a functionality to add and subtract the `TA::DistArray` objects without having to descend to each tile separately.

The operators `+`, `-`, `+=`, and `-=` would promote a neater code.

**Comment by justusc** [comment]
The `-`, `+=`, and `-=` operators follow the same pattern. Note as a side effect, you can permute the data, so be sure to pay attention to the order of the indices.

**Comment by bimalgaudel** [comment]
Wouldn't it be useful if we could have an option to do C = A + B? Of course, it's not a killer feature but still. On BTAS we can do it that way.

**Comment by pchong90** [comment]
Bimal,
TiledArray uses the technique of  [expression template](https://en.wikipedia.org/wiki/Expression_templates) for all tensor operations, which is compile time. So if you want to do tensor operations based on runtime information (I guess that's why you need this operation?), you might need to look at the `DistEval` class. These are the internal functions that do the internal evaluations. 
But you can still do things like
```
std::string str = dummy_index(A.rank());
if(plus){
    A(str) += B(str);
}
else if (minus)
{
    A(str) -= B(str);
}
```
where the function `dummy_index` will return string based on rank of tensor like this `"i1,i2,i3,i4"`. There should already be a function like this in TA.

**Comment by justusc** [comment]
If such operators were added to TA it would be probably be implemented with the expressions I showed in my earlier comment. It would have to auto generate the indices. You are of course free to add such an operator in your application, if you want to. But such an interface is limited because it doesn’t allow the user to take advantage of any of the other expression features of TA. Eventually, more features would be “needed” in this second interface and suddenly you have two nearly identical interfaces, with one that is limited because you can’t do permutations. Thus your code would have to use both, and both would have to be maintained. 

I am not sure that the comparison to BTAS is valid because, as far as I am aware, it does not support tensor expressions or indexed tensor in the same way that TA does. 

I think the interface as it is fulfills the need for a simple way to add distributed arrays without having to manipulate the tiles directly. I can see why you feel that specifying the indices for each tensor is cumbersome for a simple addition or subtraction option, but it is very convenient once you start doing anything more complex that involves permitting or contracting tensors. 

Going back to your original question for a moment, there are helper function that you can use to initialize tiles and modify tiles outside expressions. You should not need to write code that manipulates tiles directly except via these helper functions. For standard tensor arithmetic you shouldn’t need to manipulate tiles directly at all.

**Comment by bimalgaudel** [comment]
Thanks for the responses guys. I am closing this issue.
