### ISSUE TITLE
complicated expression with Lazy tensor fails.

### ISSUE THREAD

**Issue by shiozaki** [ValeevGroup/tiledarray#50]
The same example with lazy tensor fails. If we break up the expression (see if blocks), it works. **The error occurs only when >1 MPI processes are used**. The error message is:
```
[shiozaki@zinc src]$ mpirun -n 2 ./a.out 
MADNESS runtime initialized with 31 threads in the pool and affinity -1 -1 -1
!! ERROR TiledArray: The Array has not been initialized, likely reason: it was default constructed and used.
```
Here is the complete program:
```
#include <tiledarray.h> // for TiledArray library
class Gen {
  public:
    Gen() { }
    template <typename Index> double operator()(const Index& i) { return 1.0; }
};

template<typename DataType, int N, typename Gen>
class LazyTensor {
  private:
    TiledArray::Array<DataType, N, LazyTensor>* owner_;
    std::array<size_t, N> index_;
    Gen* gen_;

  public:
    using value_type = DataType;
    using eval_type = TiledArray::Tensor<DataType>;
    using range_type = typename eval_type::range_type;

    template <typename Archive>
    void serialize(Archive& ar) {
//    assert(false);
    }

  public:
    LazyTensor(TiledArray::Array<DataType, N, LazyTensor>* o, const std::array<size_t, N>& i, Gen* gen)
     : owner_(o), index_(i), gen_(gen) {
    }

    LazyTensor(const LazyTensor& other) : owner_(other.owner_), index_(other.index_), gen_(other.gen_) { }
    LazyTensor() { }

    LazyTensor& operator=(const LazyTensor& other) {
      owner_ = other.owner_;
      index_ = other.index_;
      gen_   = other.gen_;
      return *this;
    }

    operator eval_type () const {
      eval_type tile(owner_->trange().make_tile_range(index_));
      auto* ptr = tile.data();
      for (auto& i : tile.range())
        *ptr++ = (*gen_)(i);
      return tile;
    }
};


namespace TA = TiledArray;

int main(int argc, char** argv) {
  // Initialize runtime
  madness::World& world = madness::initialize(argc, argv);

  // Construct tile boundary vector
  std::vector<std::size_t> tile_boundaries;
  for(std::size_t i = 0; i <= 16; i += 4)
    tile_boundaries.push_back(i);

  // Construct a set of TiledRange1's
  std::vector<TiledArray::TiledRange1>
    ranges(4, TiledArray::TiledRange1(tile_boundaries.begin(), tile_boundaries.end()));
  std::vector<TiledArray::TiledRange1>
    ranges3(3, TiledArray::TiledRange1(tile_boundaries.begin(), tile_boundaries.end()));


  // Construct the 2D TiledRange
  TA::TiledRange trange(ranges.begin(), ranges.end());
  TA::TiledRange trange3(ranges3.begin(), ranges3.end());

  // Construct array objects.
  TA::Array<double, 4> a(world, trange);
  TA::Array<double, 4> b(world, trange);
  TA::Array<double, 3> c(world, trange3);

  using Lazy = LazyTensor<double,3,Gen>;
  TA::Array<double, 3, Lazy> d(world, trange3);
  Gen gen;
  for (auto& t : d.trange().tiles())
    if (d.is_local(t)) {
      std::array<size_t, 3> index;
      std::copy(t.begin(), t.end(), index.begin());
      madness::Future<typename TA::Array<double, 3, Lazy>::value_type> tile(Lazy(&d, index, &gen));
      d.set(t, tile);
    }


  // Initialize a and b.
  a.fill_local(0.0);
  b.fill_local(0.0);
  c.fill_local(0.0);

#if 1
  // THIS FAILS
  a("x6,a3,x5,a1") = b("x0,a1,x2,a3") * c("o4,x0,x2") * d("a1,a3,o4") * c("o4,x5,x6");
#else
  // THIS WORKS
  TA::Array<double, 3> tmp1(world, trange3);
  TA::Array<double, 3> tmp2(world, trange3);
  tmp1("a1,a3,o4") = b("x0,a1,x2,a3") * c("o4,x0,x2");
  tmp2("a1,a3,o4") = tmp1("a1,a3,o4") * d("a1,a3,o4");
  a("x6,a3,x5,a1") = tmp2("a1,a3,o4") * c("o4,x5,x6");
#endif

  // Wait for all the computation to complete before exiting
  world.gop.fence();

  madness::finalize();
  return 0;
}
```

**Comment by shiozaki** [comment]
In addition, only in the situation when the program fails (>1 MPI processes and the first block), Madness tries to serialize the Lazy tensor (hence assert being commented out). I think this should not happen.

**Comment by justusc** [comment]
I think the source of the error is the pointer to the `Array` object in your lazy tiles are not initialized correctly. Tiles (including lazy tiles) can and will be moved during expression evaluation. Since your serialization function does nothing, the tile evaluation function is probably throwing an exception when calling `owner_->trange().make_tile_range(index_)`. I am not sure why the second set of equations work. Perhaps there is a difference in the way data is distributed.

It is necessary to move tiles during contractions and other operations. The logic of this is to construct the tile at the point of use, rather than constructing it then moving the data. I recommend reformulating the tile data so that it does not contain a reference to the `Array`, which will make it easier to serialize. Instead, store construct and store the tile range when the lazy tile is constructed.

I will verify the error in a little bit.

**Comment by justusc** [comment]
Also, you may want to consider using the `Array::init_local_tiles()` function, to initialize tiles. If you can make it work in your code, then construction of tiles will automatically be parallelized.

http://valeevgroup.github.io/tiledarray_doc/v0.4.4-alpha/class_tiled_array_1_1_array.html#a6562470821b5af963d044273a971cca7

**Comment by shiozaki** [comment]
I believe this is how lazy tensor are used in mpqc, though.



On Nov 26, 2015, at 6:21 PM, Justus Calvin <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, you may want to consider using the Array::init_local_tiles() function, to initialize tiles. If you can make it work in your code, then construction of tiles will automatically be parallelized.

http://valeevgroup.github.io/tiledarray_doc/v0.4.4-alpha/class_tiled_array_1_1_array.html#a6562470821b5af963d044273a971cca7

-

**Comment by justusc** [comment]
The TA code in MPQC is not suited for distributed memory. There TA is used as a wrapper around old MPQC constructs. It was only ever intended to be an intermediate solution.

**Comment by justusc** [comment]
Also, we encountered a lifetime bug related to the lazy tile storing a pointer to an array. There is a simple workaround to the problem, but it is best to avoid the issue by not storing array pointers in the tiles.

**Comment by shiozaki** [comment]
@evaleev This code has been based on the code in MPQC that you suggested me to look at. Please explain.

**Comment by shiozaki** [comment]
@justusc Since I gave you a complete code, can you give me a complete code that works? Please note that "return 1.0" (line 5) is actually more complicated in the actual code.

**Comment by justusc** [comment]
I verified the source of your error. It is indeed caused by improperly serialized tiles. Below is a modified version of your LazyTile that clearly identifies the error. Note the changes to the default constructor and the eval_type type conversion operator.

```C++
template<typename DataType, int N, typename Gen>
class LazyTensor {
  private:
    TiledArray::Array<DataType, N, LazyTensor>* owner_;
    std::array<size_t, N> index_;
    Gen* gen_;

  public:
    using value_type = DataType;
    using eval_type = TiledArray::Tensor<DataType>;
    using range_type = typename eval_type::range_type;

    template <typename Archive>
    void serialize(Archive& ar) {
//    assert(false);
    }

  public:
    LazyTensor() : owner_(nullptr), index_(), gen_(nullptr) { }

    LazyTensor(TiledArray::Array<DataType, N, LazyTensor>* o, const std::array<size_t, N>& i, Gen* gen)
     : owner_(o), index_(i), gen_(gen) {
    }

    LazyTensor(const LazyTensor& other) : owner_(other.owner_), index_(other.index_), gen_(other.gen_) { }

    LazyTensor& operator=(const LazyTensor& other) {
      owner_ = other.owner_;
      index_ = other.index_;
      gen_   = other.gen_;
      return *this;
    }

    operator eval_type () const {
      if(! owner_) { /// <<<<<<<<<<<<<<<<<<<<<<<<<<<<< Check for error here
        std::cout << "OOPS, Tile not initialized!\n";
        MPI_Abort(MPI_COMM_WORLD, 1);
      }
      eval_type tile(owner_->trange().make_tile_range(index_));
      auto* ptr = tile.data();
      for (auto& i : tile.range())
        *ptr++ = (*gen_)(i);
      return tile;
    }
};
```

**Comment by justusc** [comment]
Below is the modified version of your code. Changes I made to the code:

1. Implemented  the serialization function of `LazyTensor`
2. Changed the data members of `LazyTensor` to hold a TA::Range object and a copy of Gen.
3. Added compiler generated constructors/destructor/assignment operators. Only the default constructor is required for compatibility with TA.
4. Added a serialization function to `Gen`, which is required to serialize `LazyTensor` data members.
5. The tiles of the `d` array are initialized with `TA::Array::init_local_tiles()`.

If your generator requires access to a non-trivial amount of shared data, you need to take special care when serializing the tiles. In this case, I recommend you add a static data member to `Gen` to store local data or use a global variable to store key-value data that your tile can access during deserialization.

```C++
#include <tiledarray.h> // for TiledArray library

namespace TA = TiledArray;

class Gen {
public:
  template <typename Index> double operator()(const Index& i) const { return 1.0; }

  template <typename Archive>
  void serialize(Archive& ar) {
    // Serialize data members here ...
  }
};

template<typename DataType, typename Gen>
class LazyTensor {
  public:
    using value_type = DataType;
    using eval_type = TA::Tensor<value_type>;
    using range_type = typename eval_type::range_type;

  private:
    range_type range_;
    Gen gen_;

  public:
    // Compiler generated functions
    LazyTensor() = default;
    LazyTensor(const LazyTensor<DataType, Gen>&) = default;
    LazyTensor(LazyTensor<DataType, Gen>&&) = default;
    ~LazyTensor() = default;
    LazyTensor<DataType, Gen>& operator=(const LazyTensor<DataType, Gen>&) = default;
    LazyTensor<DataType, Gen>& operator=(LazyTensor<DataType, Gen>&&) = default;

    // Tile constructor
    LazyTensor(const TiledArray::Range& range, const Gen& gen) :
      range_(range), gen_(gen)
    { }

    // Tile generator function
    operator eval_type () const {
      eval_type tile(range_);
      for(typename eval_type::size_type i = 0ul; i < tile.size(); ++i)
        tile[i] = gen_(i);
      return tile;
    }

    // Serialization function
    template <typename Archive>
    void serialize(Archive& ar) {
      ar & range_ & gen_;
    }
};


int main(int argc, char** argv) {
  // Initialize runtime
  madness::World& world = madness::initialize(argc, argv);

  // Construct tile boundary vector
  std::vector<std::size_t> tile_boundaries;
  for(std::size_t i = 0; i <= 16; i += 4)
    tile_boundaries.push_back(i);

  // Construct a set of TiledRange1's
  std::vector<TiledArray::TiledRange1>
    ranges(4, TiledArray::TiledRange1(tile_boundaries.begin(), tile_boundaries.end()));
  std::vector<TiledArray::TiledRange1>
    ranges3(3, TiledArray::TiledRange1(tile_boundaries.begin(), tile_boundaries.end()));


  // Construct the 2D TiledRange
  TA::TiledRange trange(ranges.begin(), ranges.end());
  TA::TiledRange trange3(ranges3.begin(), ranges3.end());

  // Construct array objects.
  TA::Array<double, 4> a(world, trange);
  TA::Array<double, 4> b(world, trange);
  TA::Array<double, 3> c(world, trange3);

  using Lazy = LazyTensor<double,Gen>;
  TA::Array<double, 3, Lazy> d(world, trange3);
  Gen gen;
  d.init_local_tiles([&] (const TiledArray::Range& range) {
    return Lazy(range, gen);
  });

  // Initialize a and b.
  a.fill_local(0.0);
  b.fill_local(0.0);
  c.fill_local(0.0);

#if 1
  // THIS FAILS
  a("x6,a3,x5,a1") = b("x0,a1,x2,a3") * c("o4,x0,x2") * d("a1,a3,o4") * c("o4,x5,x6");
#else
  // THIS WORKS
  TA::Array<double, 3> tmp1(world, trange3);
  TA::Array<double, 3> tmp2(world, trange3);
  tmp1("a1,a3,o4") = b("x0,a1,x2,a3") * c("o4,x0,x2");
  tmp2("a1,a3,o4") = tmp1("a1,a3,o4") * d("a1,a3,o4");
  a("x6,a3,x5,a1") = tmp2("a1,a3,o4") * c("o4,x5,x6");
#endif

  // Wait for all the computation to complete before exiting
  world.gop.fence();

  madness::finalize();
  return 0;
}
```

**Comment by justusc** [comment]
> @evaleev This code has been based on the code in MPQC that you suggested me to look at. Please explain.

To be clear, the only area that I am aware of in MPQC where it is not appropriate for distributed-memory operations is in the lazy tile code. This is because tensor data is stored in files. @evaleev used lazy tile wrappers as an input mechanism for TA arrays; this was only intended as a means of interfacing old MPQC code with new TA-based code. It is my understanding that the way file data is stored and some implementation details precludes distributed-memory access to the file data. Therefore, some of the design decision with respect to lazy tiles in MPQC did not take into account serialization and/or data movement.

Also, MPQC was the first application that used TA. Since that time, our understanding of best practices has become more mature. Furthermore, I have added a number of convenience features to TA which are not used in MPQC.

**Comment by justusc** [comment]
I recommend taking a different approach to your problem. Since you are doing an element wise modification of your tile data, you can use `foreach_inplace`. It avoids extra hassle serializing lazy tiles, it avoids the extra memory overhead of storing the lazy tiles, minimizes memory access, and results in more compact code. You can also reuse the operator in other parts of our code just like you would a lazy tensor. The only down side to this approach is that you cannot write the expression as a single line, but I think the benefits outweigh this cost.

Below is an example code.

```C++
#include <tiledarray.h> // for TiledArray library

namespace TA = TiledArray;

class TileOp {
public:
  float operator()(TA::Tensor<double>& tile) const {
    double norm_squared = 0.0;
    for(TA::Tensor<double>::size_type i = 0ul; i < tile.size(); ++i) {

      // Set tile data
      tile[i] = std::sqrt(tile[i]);

      // Update tile norm
      norm_squared += tile[i] * tile[i];
    };

    // Compute the tile norm
    return std::sqrt(norm_squared);
  }
};


int main(int argc, char** argv) {
  // Initialize runtime
  madness::World& world = madness::initialize(argc, argv);

  // Construct tile boundary vector
  std::vector<std::size_t> tile_boundaries;
  for(std::size_t i = 0; i <= 16; i += 4)
    tile_boundaries.push_back(i);

  // Construct a set of TiledRange1's
  std::vector<TiledArray::TiledRange1>
    ranges(4, TiledArray::TiledRange1(tile_boundaries.begin(), tile_boundaries.end()));
  std::vector<TiledArray::TiledRange1>
    ranges3(3, TiledArray::TiledRange1(tile_boundaries.begin(), tile_boundaries.end()));


  // Construct the 2D TiledRange
  TA::TiledRange trange(ranges.begin(), ranges.end());
  TA::TiledRange trange3(ranges3.begin(), ranges3.end());

  // Construct array objects.
  TA::Array<double, 4> a(world, trange);
  TA::Array<double, 4> b(world, trange);
  TA::Array<double, 3> c(world, trange3);

  // Initialize a and b.
  a.fill_local(0.0);
  b.fill_local(0.0);
  c.fill_local(0.0);

  // THIS WORKS
  TA::Array<double, 3> tmp;
  tmp("a1,a3,o4") = b("x0,a1,x2,a3") * c("o4,x0,x2");
  foreach_inplace(tmp, TileOp());
  a("x6,a3,x5,a1") = tmp("a1,a3,o4") * c("o4,x5,x6");

  // Wait for all the computation to complete before exiting
  world.gop.fence();

  madness::finalize();
  return 0;
}
```

**Comment by shiozaki** [comment]
Does this foreach_inplace work with block expressions? In BAGEL I am doing this operation to part of the amplitudes (again, typical of multireference theories).

**Comment by shiozaki** [comment]
FYI
https://github.com/nubakery/bagel/blob/tiledarray/src/smith/spinfreebase_update.cpp
https://github.com/nubakery/bagel/blob/tiledarray/src/smith/tatensor.h
https://github.com/nubakery/bagel/blob/tiledarray/src/smith/lazytensor.h

mind that my a("x6,a3,x5,a1") is actually returning blocks
https://github.com/nubakery/bagel/blob/tiledarray/src/smith/tatensor.h#L240

**Comment by shiozaki** [comment]
never mind these two comments - intermediates in this context are single-block, so that should not be a problem..

**Comment by justusc** [comment]
Currently, foreach and foreach_inplace modify the entire array. In the case where you are modifying an intermediate, foreach should work as I presented it in my previous post. You can also implement the foreach functor to only update a sub-block of the array (based on the range of the tile) and leave other tiles in the array unmodified.

You can make the functors as complex as necessary, but keep in mind that the functor will copied into each task object. Therefore, you may need to wrap functor data into a pimpl/shared_ptr.

**Comment by evaleev** [comment]
@shiozaki as @justusc explained, the mpqc example was flawed as it was designed for particular use case (using TA as expression engine for on-disk data) and did not need to worry about serialization.

Solution suggested by @justusc works because the tiles contain *all* context they need for serialization, but it may sometimes be necessary for LazyTiles to refer to bigger chunk of context than in this example; in that case pointer to Array may be what you want. All you have to do in that case is serialize not the bare pointer by Array's global id and use that id on the other end to grab the corresponding pointer. All global MADworld objects like TiledArray::Array live in a global namespace and have corresponding unique id (implemented by madness::uniqueidT defined in madness/src/lib/world/uniqueid.h). madness::World provides method ptr_from_id() that converts global id to (local) object pointer.

**Comment by justusc** [comment]
@evaleev 
> but it may sometimes be necessary for LazyTiles to refer to bigger chunk of context than in this example; in that case pointer to Array may be what you want.

I advise against storing a raw pointer to the array inside tiles. This design has the potential to cause lifetime issues as the tiles can outlive the array that holds them.

> All global MADworld objects like TiledArray::Array live in a global namespace and have corresponding unique id (implemented by madness::uniqueidT defined in madness/src/lib/world/uniqueid.h). madness::World provides method ptr_from_id() that converts global id to (local) object pointer.

This is true, but array objects are not stored in the global registry. Thus, you cannot use the world object to obtain a copy of the array. The array object does have a globally unique id that can be used in a user defined local registry if needed.

**Comment by shiozaki** [comment]
I am revising all my code using foreach_inplace... but these lazy tensors are necessary in other contexts, so thanks for the comments.

One more thing - what is the quickest possible way to eliminate i0 from the following code? This quantity is the largest quantity in the calculation and cannot be replicated. Note that **t("...") and r("...") are returning blocks**. We cannot modify r as well (in MRCI, we need to keep it for the Davidson solver)
```
        TATensor<DataType,4> i0(vector<IndexRange>{closed_, virt_, closed_, virt_}, true);
        if (is_same<DataType,double>::value)
          i0("c0,a1,c2,a3") = r("c0,a1,c2,a3") * (1.0/6.0) + r("c0,a3,c2,a1") * (1.0/12.0);
        else
          i0("c0,a1,c2,a3") = r("c0,a1,c2,a3") * 0.25;
        foreach_inplace(i0, [&](typename TATensor<DataType,4>::value_type& tile) {
          auto range = tile.range();
          for (auto& i : range)
            tile[i] /= - eig(i[3]+ncore) + eig(i[2]+nocc) - eig(i[1]+ncore) + eig(i[0]+nocc);
        }); 
        t("c0,a1,c2,a3") -= i0("c0,a1,c2,a3");
```
In my original code it did this without making any copy.

**Comment by evaleev** [comment]
I advise against storing a raw pointer to the array inside tiles. This
> design has the potential to cause lifetime issues as the tiles can outlive
> the array that holds them.
>
That's a good point. I think the user needs to manage the lifetime
carefully. Bottom line is that it is not realistic to keep all context
completely within the tile, there must be a way to refer to
globally-accessible context.

This is true, but array objects are not stored in the global registry.
> Thus, you cannot use the world object to obtain a copy of the array. The
> array object does have a globally unique id that can be used in a user
> defined local registry if needed.
>
Also good point: I keep forgetting that Array's are not WorldObject's, only
their key part (DistributedStorage). Might be a good idea to make Array (at
least ArrayImpl) a WorldObject.

**Comment by justusc** [comment]
> I am revising all my code using foreach_inplace... but these lazy tensors are necessary in other contexts, so thanks for the comments.

Sounds good.

> One more thing - what is the quickest possible way to eliminate i0 from the following code?

The only improvement in terms of memory use I can see is to do a second `foreach_inplace` to replace these -= operation. The reason is because += and -= do not actually do an in-place update. Internally, `a += x` is treated `a = a + x`. If the expression generates a temporary, e.g. `a += x * y`, then `a` is added to the temporary and the temporary replaces the data in `a`. In the case of a temporary, this implementation is memory optimal and safe in a distributed memory environment. In the case where there is no temporary generated in the expression, extra memory is needed to ensure data consistency. The memory is cleaned up fairly quickly but not immediately. I only recommend this if minimum memory is critical here.

You can also enclose `i0` inside curly brackets and call Array::wait_for_lazy_cleanup() to wait for memory cleanup before proceeding. 

In addition, I would change the loop in your code to use 4 explicit loops to avoid extra computation. Range iterators are expensive and should only be used if there is no other option.

**Comment by justusc** [comment]
@shiozaki 
I have been considering your set of equations and the advice in my previous post. First, using `foreach_inplace` in a binary operation is not a good idea since the only way to do it would be to invoke an array find operation, which involves waiting communication (forcing a future), which would most likely result in a deadlock. Therefore, the code you provided is the best solution.

**Comment by shiozaki** [comment]
OK thanks. I have replaced the range loops with explicit loops.
