### ISSUE TITLE
How to shallow copy tiles?

### ISSUE THREAD

**Issue by ryanmrichard** [ValeevGroup/tiledarray#58]
Given a large blocked tensor, I am trying to build new tensors, whose tiles are actually those from the larger tensor.  

For example, pretend that my large tensor is a matrix and it is tiled in a 2 by 2 format.  I now want to make another matrix whose only tile is say the second tile of the larger matrix (application being to grabbing say the alpha or beta blocks of a quantity).  Moreover, I do not want to deep copy the tile; deep copying the meta data is acceptable.  I presume there is a way to do this?  

Here is a stripped down version of what I have tried:
```C++
int main(int argc, char** argv){
     TiledArray::World& world=madness::initialize(argc,argv);
     std::array<size_t,3> Boundaries({0,4,8});

     typedef TiledArray::TiledRange1 Range1_t;
     typedef TiledArray::TiledRange Range_t;
     typedef TiledArray::Array<double,2> Matrix;

     std::vector<Range1_t>
        LargeRange(2,Range1_t(Boundaries.begin(),Boundaries.end())),
        SmallRange(2,Range1_t(Boundaries.begin(),Boundaries.end()-1));

     Matrix Large(world,Range_t(LargeRange.begin(),LargeRange.end())),
            Small(world,Range_t(SmallRange.begin(),SmallRange.end()));

     //Fill each block with its ordinal number
     Matrix::iterator LI=Large.begin(),LIEnd=Large.end();
     for(size_t i=0;i<4;++i)
        if(Large.is_local(i))
           Large.set(i,Matrix::value_type(Large.trange().make_tile_range(i),i));
     Small.set(0,Large.find(1));

      if(world.rank()==0) std::cout<<"Large"<<std::endl;
      std::cout<<Large;
      if(world.rank()==0)std::cout<<std::endl<<"Small"<<std::endl;
      std::cout<<Small;
}//End main
```

Using one MPI process this produces:
```
Large
0: [ [0,0], [4,4] ) { 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 }
1: [ [0,4], [4,8] ) { 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 }
2: [ [4,0], [8,4] ) { 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 }
3: [ [4,4], [8,8] ) { 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 }

Small
0: [ [0,4], [4,8] ) { 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 }
```
as (somewhat) expected (I would have expected the small tensor to be labeled as 0:[[0,0],[4,4]), but the indices from the large tensor are alright too).  All subsequent, single process, tries produce the same output.

With two MPI processes I get:
```
terminate called after throwing an instance of 'TiledArray::Exception'
  what():  TiledArray: exception at /xxx/TiledArray/distributed_storage.h(83): Tile has already been assigned.
```

As a sanity check I tried:
```C++
     Small.set(0,Large.find(1).get());
```
and have been met with the same result.  Thinking this is a data locality issue, I then tried:
```C++
    if(Small.is_local(0))Small.set(0,Large.find(1));
```
and get:
```
!! MADNESS ERROR: Mutex::lock() failed acquiring mutex
!! MADNESS ERROR: Mutex error EINVAL
!! MADNESS ERROR: The value specified by mutex does not refer to an initialized mutex object.
A madness exception occurred. Place a break point at madness::exception_break to debug.
```
Trying the get() member of the returned future leads to a similar error, as does ensuring that the large tile is local [both with and without the get() member]:
```C++
    if(Small.is_local(0)&&Large.is_local(1))Small.set(0,Large.find(1));
```
Completing the power set:
```C++
     if(Large.is_local(1))Small.set(0,Large.find(1).get());
```
leads to the same error as well.

Am I doing something wrong, or is this feature not supported?

**Comment by justusc** [comment]
In answer to your first question, yes, you can assign a sub-block of one tensor to another. The code looks like
```c++
Array<double,2> Small;
Small("a,b") = Large("a,b").block({0,1}, {1,2});
```
This should give the expected output. Note, you can use an initializer list as I have shown, a `std::vector`, a  `std::array`, or other object that follows the same interface.

The reason your block looked like:
```
Small
0: [ [0,4], [4,8] ) { 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 }
```
is because there is no check or adjustment tiles that are assigned with Array::set(). It assumes you are giving it the correct data.

You get an error with 2 MPI processes because there is no guard around which process is setting the tile. That is, both processes were trying to set the same tile. You were headed in the right direction with the `is_local` check when assigning the tile to `Small`, but your logic was off. It should have been
```c++
if(Small.is_local(0))
  Small.set(0,Large.find(1));
```

The error 
```
!! MADNESS ERROR: Mutex::lock() failed acquiring mutex
!! MADNESS ERROR: Mutex error EINVAL
!! MADNESS ERROR: The value specified by mutex does not refer to an initialized mutex object.
A madness exception occurred. Place a break point at madness::exception_break to debug.
```
is most likely due to a bug in MADNESS. You should use the latest version from the main repository if not already.

Give that a try and let me know if you have further difficulties.

**Comment by ryanmrichard** [comment]
I downloaded the newest version of Madness and Tiled Array.  For whatever reason I am now having quite a bit of trouble compiling both of them.  Maybe all of these problems are just my system, but for some of the Madness examples (`cc2.cc` is the first one that won't compile for me) they can't find their include files, specifically the includes in `src/app/chem`.  I manually fixed that with a static link in my source tree and then Madness compiled cleanly.  Next, while trying to get Tiled Array to use this version of Madness I can't for the life of me seem to link the test created in `madness.cmake`.  I have set both `CMAKE_REQUIRED_LIBRARIES` and `Madness_LIBRARIES`; inserting a print statement, right before the test, shows they are set appropriately too.  In desperation, I finally just commented the check out and was able to build it.  

At the linking stage of the test program, I learned that `TILEDARRAY_ALIGNMENT` is no longer being set for some reason, which I went ahead and set to 16 manually.  Additionally the bug I pointed out in https://github.com/ValeevGroup/tiledarray/issues/52 seems to have re-manifested.   Finally, Madness wants to link against very specific versions of my MPI libraries, such as `libmpich.so.3`, which doesn't actually exist.  I created the necessary static links and finally the test program compiled.  I have no idea why I ran into so many problems as the builds had worked flawlessly when I opened this issue.

Anyways, It does indeed appear to work as expected, so thank you.

BTW, you appear to be right that the Madness message is an error; there is this issue on its GitHub issues tracker:
https://github.com/m-a-d-n-e-s-s/madness/issues/163
, but the newest version of Madness seems to have alleviated the problem, at least for me.

**Comment by justusc** [comment]
I apologize for all the difficulty you are having. Can you create an issue for the MADNESS build error? Please include your configure script and the relevant error message. I will look into fixing it.

To build with an external MADNESS build, you can set `Madness_ROOT_DIR` to the <madness install prefix>. 

The `CMAKE_REQUIRED_LIBRARIES` and `Madness_LIBRARIES` variables are not intended for users.

I am not seeing an error with undefined `TILEDARRAY_ALIGNMENT`. I recently moved the definition to the config.h file, so it is possible that the it is no longer being included somewhere. Can you file an issue on this with the full error output? I will try to fix this ASAP.

I am not sure  how the fix to #52 was lost. Blame says the line has not change in a long while. I have pushed the fix again.

I do not think that anyone has tracked down the origin of the m-a-d-n-e-s-s/madness#163 issue. However, the mutex error you saw is known to be caused by a stack overflow, which I fixed a few months ago but is not included in the latest MADNESS release. That issue could be related or not. No one has brought it up since I fixed the stack overflow issue, so maybe it has been fixed.

**Comment by evaleev** [comment]
@ryanmrichard the issues with separate compilation of MADNESS and TiledArray cannot be adequately solved with our resources, so the preferred way to build MADNESS is as a "subproject" in TiledArray. This mechanism at least ensures that you will use the recommended version of MADNESS that someone managed to use at least once. Minimal/no hacking of the build system should be necessary then.

**Comment by ryanmrichard** [comment]
Everything seems like it is back to working out of the box now.  Thank you so much.

**Comment by justusc** [comment]
Good to hear. Again, sorry about the disruption. You caught us in the middle of updating our configure scripts.

FYI, the cmake variable `Madness_ROOT_DIR` was just changed to MADNESS_ROOT_DIR.
