### ISSUE TITLE
Allow SparseShape norm to be negative?

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/tiledarray#78]
I have a case that user will define the SparseShape of an Array. For example, a diagonal matrix. My current approach is to define the norm of empty tile to 0.0. However, this sparseshape will not work if my sparse threshold is also set to 0.0. 

So, would it be ok to set the norm of tile with negative value to make it a user defined empty tile? 

Currently, this is not allowed, see sparse_shape.h, line 143
```
         {
          TA_ASSERT(norm >= value_type(0));
          norm *= x * y;
          if(norm < threshold) {
            norm = value_type(0);
            ++zero_tile_count;
          }
        };
```

**Comment by justusc** [comment]
No, negative values for shares shape is not a good idea since it is not in the valid range for shapes and it could yield incorrect shapes in expressions. Also, setting threshold to zero defeats the purpose of the sparse tensor. Finally, a zero threshold would give unexpected behavior due to numerical noise. 

The problem you are having is that are having is that the norm of the diagonal tiles are very small because they are mostly zero. This same problem occurs with sparse identity tensors. The best solution is to lie to TA and set a higher norm for the diagonal tiles. For the identity tensor, it is best to set the diagonal tile norms to the number of elements in tile, which will give a value of one after the norm is normalized. Alternatively, you can set it to the minimum for a non-zero tile, which is 

( (threshold) + (epsilon) ) * (tile volume)

Both methods will give you non-zero tiles that you want to keep. You may need to experiment with the norm value to get the behavior you want.

**Comment by pchong90** [comment]
Ok. I got it. Currently I just set none-zero tile to  `numeric_limits<float>::max()`
I think it would be useful to distinguish user defined shape(forced shape) with other shapes. What do you think?

**Comment by justusc** [comment]
It is not a good idea to set the norm to max either. Remember that other shapes will be computed from the values in the input tensors. If you set it to max, the output is undefined and you will likely get erroneous results. Pick some value that is based on the tile volume. Also, don't generate a range object for each tile, compute it yourself.
