### ISSUE TITLE
`block` operation on replicated `TA::DistArray`

### ISSUE THREAD

**Issue by pchong90** [ValeevGroup/tiledarray#99]
Does `block` operation on replicated `TA::DistArray` require communication? 
I haven't read any source code related to `block` operation, but this should be a question easy to answer.

**Comment by justusc** [comment]
Yes it can result in communication. The process map used in the intermediate expression is given by the consuming tensor operation. This is done to avoid communication in distributed computation.

This deficiency can easily be fix in a few lines of code.

**Comment by pchong90** [comment]
Thanks. Another question about `block` operation. Does the task of `block` operation overlap with the task in contraction?

For example,
```
TA::DistArray A, B;
A("i,j") = X1("i,j").block(low,up);
B("i,j") = X2("i,j").block(low,up);
C("i,j") = A("i,k") * B("k,j");
```
would this way of writing the code makes any difference?
```
auto left = X1("i,j").block(low,up);
auto right = X2("i,j").block(low,up);
C("i,j") = left * right;
```

**Comment by justusc** [comment]
As a general rule you can expect some overlap between at most two expressions. The last tensor operation will overlap with the next expression. The idea is to allow some overlap, but you do not want too much otherwise memory usage will blowup. 

If an expression evaluation is fast and there are no dependencies between the sequential expressions, then it is possible to get more overlap. However this is not guaranteed.

So in you specific examples, you might get overlap between the three expressions in your first example. In your second example you will definitely get overlap.

One other thing to not is that the first example does not allow for automatic memory cleanup of the two inputs, but the second one does. So the second is the preferred unless you intend to reuse the inputs.

**Comment by pchong90** [comment]
Thanks. This is helpful.
